Update conversion calc. impl. and test it
dethcrypto/tools pull request #23
Opened 2022-03-16 13:20 UTC by 7sne

2022-03-16 16:01 UTC, hasparus approved these changes

2022-03-16 16:01 UTC, hasparus commented on pages/eth-unit-conversion.test.tsx
> +    const errorField = (await root.findByTestId('error')) as HTMLElement
Do we need this `as HTMLElement` in this case?

2022-03-16 16:01 UTC, hasparus commented on pages/token-unit-conversion.test.tsx
> +    const errorField = (await root.findByTestId('error')) as HTMLElement
I'm not quite sure `as HTMLElement` is needed here. Isn't this already `HTMLElement`?

2022-03-17 00:34 UTC, krzkaczor commented
I get an error at my face when I open token unit calc :( There should be some a reasonable defaults. 

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/1814312/158713564-17bd7000-cf09-4d21-a162-ebfb85345060.png">

2022-03-17 00:35 UTC, krzkaczor requested changes

2022-03-17 00:35 UTC, krzkaczor commented on misc/unitSchema.ts
> +    .min(1, { message: 'The value must be minimum 1 numbers long' })
```suggestion
    .min(1, { message: 'The value must be bigger or equal to 1' })
```

2022-03-17 00:35 UTC, krzkaczor commented on misc/unitSchema.ts
> +    .max(26, { message: 'The value must be maximum 26 numbers long' }),
```suggestion
    .max(26, { message: 'The value must be less or equal to 26' }),
```

2022-03-18 10:47 UTC, krzkaczor approved these changes

2022-03-18 11:04 UTC, merged